name: Deploy .NET Core app to IIS

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubunntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'  # your version

    - name: Publish .NET Core app
      run: dotnet publish -c Release -o published

    - name: Deploy to IIS Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.IIS_SERVER_IP }}
        username: ${{ secrets.IIS_USERNAME }}
        password: ${{ secrets.IIS_PASSWORD }}
        script: |
          cd C:\inetpub\MyApp
          del * /Q
          xcopy /E /I /Y C:\Users\runneradmin\published\* C:\inetpub\MyApp\
          iisreset
