name: Deploy .NET app to Windows VM
 
on:
  workflow_dispatch:  # Allows manual triggering
 
jobs:
  deploy:
    runs-on: [self-hosted, X64, Windows]  # Targets Windows self-hosted runners
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.203  # Replace with your desired .NET version
      - name: Restore NuGet packages
        run: dotnet restore actions/aspnet6/aspnet6.csproj
      - name: Build the application 
        run: dotnet build actions/aspnet6/aspnet6.csproj --configuration Release --no-restore
      - name: Publish the application
        run: dotnet publish actions/aspnet6/aspnet6.csproj --configuration Release --no-build -o ${{ github.workspace }}/publish

      - name: Deploy to C:\inetpub\wwwroot
        run: |
          $TargetPath = "C:\inetpub\wwwroot"
          # Create directory if it doesn't exist
          if (-not (Test-Path -Path $TargetPath)) {
            New-Item -ItemType Directory -Path $TargetPath -Force
            Write-Host "Target directory created"
          }
          # Clean existing files in the target directory
          Remove-Item -Path "$TargetPath\*" -Recurse -Force -ErrorAction SilentlyContinue
          Write-Host "Target directory cleaned"
          # Copy new files directly from the publish folder
          Copy-Item -Path "${{ github.workspace }}\publish\*" -Destination $TargetPath -Recurse -Force
          Write-Host "Files deployed successfully to $TargetPath"
        shell: powershell


